### PR TITLE
Removed search shortcode and added JS instead

### PR DESCRIPTION
**Pull request by DaveyDevs**

### CODE REVIEW

**Comment by nick-dolf** [comment]
I'm getting a null reference on ivory search and a console error:
 "Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at (index):283"

**Comment by nick-dolf** [comment]
is it working for you on a specific browser?

**Comment by DaveyDevs** [comment]
@nick-dolf Ah yeah! As part of the update, we have to put the search into the Header via the Ivory Search settings - 

image

Let me know if that does the trick!

**Comment by nick-dolf** [comment]
image

still getting weird results

**Comment by nick-dolf** [comment]
ahh, figured it out. 
image
image

i needed this combo.

**Review by nick-dolf — APPROVED** [review]
Excellent, this should make updating easier

**Pull request merged**
